### 가족관계 등록
POST http://localhost:8080/residents/1/relationship
Content-Type: application/json

{
  "familySerialNumber": 123,
  "familyRelationshipCode": "father"
}

### 가족관계 수정
PUT http://localhost:8080/residents/1/relationship/2
Content-Type: application/json

{
  "familyRelationshipCode": "mother"
}

### 가족관계 삭제
DELETE http://localhost:8080/residents/1/relationship/2