###등록
POST http://localhost:8080/residents
Content-Type: application/json

{
  "residentSerialNumber": 1,
  "name": "김씨",
  "residentRegistrationNumber": "123456-0000000",
  "genderCode": "M",
  "birthDate": "1998-01-01T03:00:00",
  "birthPlaceCode": "Gimhae",
  "registrationBaseAddress": "김해시 금관대로",
  "deathDate": null,
  "deathPlaceCode": null,
  "deathPlaceAddress": null
}

###업데이트

PUT http://localhost:8080/residents/123
Content-Type: application/json

{
  "residentSerialNumber": 1,
  "name": "김씨",
  "residentRegistrationNumber": "123456-0000000",
  "genderCode": "M",
  "birthDate": "1998-01-01T03:00:00",
  "birthPlaceCode": "Gimhae",
  "registrationBaseAddress": "김해시 금관대로",
  "deathDate": "2023-01-01T00:00:00",
  "deathPlaceCode": "Seoul",
  "deathPlaceAddress": "서울특별시 강남구"
}